version: '3.3'
services:
    payara-full:
        build: mypayara-full
        ports:
            - "8080:8080"
            - "4848:4848"
        env_file:
            - "variables.env"
        volumes:
            - ./data/payara:/opt/payara41/glassfish/domains/domain1/autodeploy
        depends_on:
            - db

    db:
        image: mysql:5.7
        ports:
            - "3336:3306"
        env_file:
            - "variables.env"
        volumes:
            - ./data/db_data:/var/lib/mysql